name: e_shop
description: Flutter eCommerce App using Firebase Firestore from Coding Cafe

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.13.2+1
  cupertino_icons: ^0.1.2
  firebase_auth: ^0.15.4
  firebase_storage: ^3.1.1
  flutter_staggered_grid_view: ^0.3.0
  fluttertoast: ^3.1.3
  image: ^2.0.7
  image_picker: ^0.6.3+1
  image_picker_web: ^2.0.2
  intl: null
  path_provider: ^0.5.0+1
  provider: ^4.0.4
  shared_preferences: ^0.5.6+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf

  assets:
    - images/welcome.png
    - images/login.png
    - images/admin.png
    - images/cash.png
